version: '3'

services:
    apache:
        image: httpd:2.4
        ports:
        - 3005:80
        container_name: apache_radius
        restart: always
        volumes:
        - ./www:/usr/local/apache2/htdocs/
