version: '3'

services:
  radius:
    build: .
    volumes:
      - ./boundaries:/app/boundaries
    container_name: corona-radius
    restart: always
    ports:
      - 3005:3000
    environment:
      REDIS_HOST: redis:6379
    depends_on:
      - redis
  redis:
    container_name: corona-radius_redis
    image: redis
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
